# Generated by Django 4.2 on 2024-06-25 12:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('responsible', models.CharField(max_length=255)),
                ('planned_budget', models.DecimalField(decimal_places=2, max_digits=10)),
                ('expected_result', models.CharField(max_length=255)),
                ('planned_deadline', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='TargetIndicator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('unit', models.CharField(max_length=50)),
                ('planned_value_per_year', models.JSONField()),
            ],
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('actual_value', models.DecimalField(decimal_places=2, max_digits=10)),
                ('deviation_reason', models.TextField()),
                ('status', models.CharField(max_length=50)),
                ('indicator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reports.targetindicator')),
            ],
        ),
        migrations.CreateModel(
            name='FinancialReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('actual_budget', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total_budget', models.DecimalField(decimal_places=2, max_digits=10)),
                ('budget_utilization', models.DecimalField(decimal_places=2, max_digits=5)),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reports.activity')),
            ],
        ),
        migrations.CreateModel(
            name='ActivityReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('actual_deadline', models.DateField()),
                ('achieved_result', models.CharField(max_length=255)),
                ('status', models.CharField(max_length=50)),
                ('completion_percentage', models.DecimalField(decimal_places=2, max_digits=5)),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reports.activity')),
            ],
        ),
    ]
