# Generated by Django 4.2 on 2024-06-26 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='planned_deadline',
            field=models.DateField(verbose_name=['%d-%m-%Y']),
        ),
    ]
