# Generated by Django 5.0.6 on 2024-06-29 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0002_alter_activity_planned_deadline'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='planned_deadline',
            field=models.DateField(verbose_name='%d.%m.%Y'),
        ),
    ]
