# Generated by Django 5.1.1 on 2024-09-12 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0004_alter_activity_planned_deadline'),
    ]

    operations = [
        migrations.CreateModel(
            name='TableOne',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Наименование целевого индикатора и показателя')),
                ('plan_value', models.FloatField(verbose_name='План на текущий год')),
                ('actual_value', models.FloatField(verbose_name='Значение на конец отчетного периода')),
            ],
        ),
        migrations.CreateModel(
            name='TableTwo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.RemoveField(
            model_name='financialreport',
            name='activity',
        ),
        migrations.RemoveField(
            model_name='report',
            name='indicator',
        ),
        migrations.DeleteModel(
            name='ActivityReport',
        ),
        migrations.DeleteModel(
            name='Activity',
        ),
        migrations.DeleteModel(
            name='FinancialReport',
        ),
        migrations.DeleteModel(
            name='Report',
        ),
        migrations.DeleteModel(
            name='TargetIndicator',
        ),
    ]
