# Generated by Django 5.1.1 on 2024-09-12 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0005_tableone_tabletwo_remove_financialreport_activity_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tableone',
            name='diff_reason',
            field=models.CharField(default='', max_length=255, verbose_name='Обоснование отклонения фактического значения'),
        ),
    ]
