# Generated by Django 5.1.1 on 2024-09-12 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0006_tableone_diff_reason'),
    ]

    operations = [
        migrations.AddField(
            model_name='tabletwo',
            name='name',
            field=models.CharField(default='s', max_length=255, verbose_name='Наименование мероприятия'),
            preserve_default=False,
        ),
    ]
