# Generated by Django 5.1.1 on 2024-09-12 18:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0008_alter_tableone_diff_reason'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tabletwo',
            name='total_actually',
        ),
        migrations.RemoveField(
            model_name='tabletwo',
            name='total_set',
        ),
    ]
