# Generated by Django 5.1.1 on 2024-09-14 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0009_remove_tabletwo_total_actually_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='InitialData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('indicator_name', models.CharField(max_length=255, verbose_name='Наименование целевого индикатора')),
                ('unit', models.CharField(max_length=50, verbose_name='Единица измерения')),
                ('plan_value', models.FloatField(verbose_name='План на текущий год')),
                ('event_name', models.CharField(max_length=255, verbose_name='Наименование мероприятия')),
                ('rf_set', models.FloatField(verbose_name='Референс')),
                ('mb_set', models.FloatField(verbose_name='МБ')),
                ('vnb_set', models.FloatField(verbose_name='ВНБ')),
                ('time_execution_plan', models.FloatField(verbose_name='Срок выполнения по плану')),
                ('expected_result', models.CharField(max_length=255, verbose_name='Ожидаемы результат')),
            ],
        ),
        migrations.CreateModel(
            name='TableThree',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_execution_actually', models.FloatField(verbose_name='Время по факту')),
                ('actual_result', models.CharField(max_length=255, verbose_name='Результат')),
            ],
        ),
        migrations.RemoveField(
            model_name='tableone',
            name='name',
        ),
        migrations.RemoveField(
            model_name='tableone',
            name='plan_value',
        ),
        migrations.RemoveField(
            model_name='tabletwo',
            name='mb_set',
        ),
        migrations.RemoveField(
            model_name='tabletwo',
            name='name',
        ),
        migrations.RemoveField(
            model_name='tabletwo',
            name='rf_set',
        ),
        migrations.RemoveField(
            model_name='tabletwo',
            name='vnb_set',
        ),
        migrations.AlterField(
            model_name='tabletwo',
            name='mb_actually',
            field=models.FloatField(verbose_name='МБ'),
        ),
        migrations.AlterField(
            model_name='tabletwo',
            name='rf_actually',
            field=models.FloatField(verbose_name='Референс'),
        ),
        migrations.AlterField(
            model_name='tabletwo',
            name='vnb_actually',
            field=models.FloatField(verbose_name='ВНБ'),
        ),
    ]
