# Generated by Django 4.2 on 2024-09-12 19:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0007_tabletwo_name'),
        ('reports', '0009_remove_tabletwo_total_actually_and_more'),
    ]

    operations = [
    ]
