# Generated by Django 5.1.1 on 2024-09-14 20:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0010_initialdata_tablethree_remove_tableone_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tableone',
            name='init',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='reports.initialdata'),
        ),
        migrations.AddField(
            model_name='tabletwo',
            name='init',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='reports.initialdata'),
        ),
    ]
