# Generated by Django 4.2 on 2024-09-12 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0010_merge_20240913_0042'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tabletwo',
            name='mb_actually',
            field=models.FloatField(verbose_name='МБ'),
        ),
        migrations.AlterField(
            model_name='tabletwo',
            name='mb_set',
            field=models.FloatField(verbose_name='МБ'),
        ),
        migrations.AlterField(
            model_name='tabletwo',
            name='name',
            field=models.CharField(default='', max_length=255, verbose_name='Наименование мероприятия'),
        ),
        migrations.AlterField(
            model_name='tabletwo',
            name='rf_actually',
            field=models.FloatField(verbose_name='Референс'),
        ),
        migrations.AlterField(
            model_name='tabletwo',
            name='rf_set',
            field=models.FloatField(verbose_name='Референс'),
        ),
        migrations.AlterField(
            model_name='tabletwo',
            name='vnb_actually',
            field=models.FloatField(verbose_name='ВНБ'),
        ),
        migrations.AlterField(
            model_name='tabletwo',
            name='vnb_set',
            field=models.FloatField(verbose_name='ВНБ'),
        ),
    ]
