# Generated by Django 5.1.1 on 2024-09-17 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0011_tableone_init_tabletwo_init'),
    ]

    operations = [
        migrations.AddField(
            model_name='tabletwo',
            name='rb_actually',
            field=models.FloatField(null=True, verbose_name='РБ'),
        ),
        migrations.AlterField(
            model_name='tabletwo',
            name='mb_actually',
            field=models.FloatField(null=True, verbose_name='МБ'),
        ),
        migrations.AlterField(
            model_name='tabletwo',
            name='rf_actually',
            field=models.FloatField(null=True, verbose_name='Референс'),
        ),
        migrations.AlterField(
            model_name='tabletwo',
            name='vnb_actually',
            field=models.FloatField(null=True, verbose_name='ВНБ'),
        ),
    ]
