# Generated by Django 5.1.1 on 2024-09-17 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0012_tabletwo_rb_actually_alter_tabletwo_mb_actually_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='initialdata',
            name='rb_set',
            field=models.FloatField(default=0.0, verbose_name='РБ'),
        ),
        migrations.AlterField(
            model_name='initialdata',
            name='mb_set',
            field=models.FloatField(default=0.0, verbose_name='МБ'),
        ),
        migrations.AlterField(
            model_name='initialdata',
            name='rf_set',
            field=models.FloatField(default=0.0, verbose_name='Референс'),
        ),
        migrations.AlterField(
            model_name='initialdata',
            name='time_execution_plan',
            field=models.FloatField(default=0.0, verbose_name='Срок выполнения по плану'),
        ),
        migrations.AlterField(
            model_name='initialdata',
            name='vnb_set',
            field=models.FloatField(default=0.0, verbose_name='ВНБ'),
        ),
    ]
