# Generated by Django 5.1.1 on 2024-09-17 21:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0013_initialdata_rb_set_alter_initialdata_mb_set_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tablethree',
            name='init',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='reports.initialdata'),
        ),
    ]
