# Generated by Django 5.1.1 on 2024-09-17 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0014_tablethree_init'),
    ]

    operations = [
        migrations.AlterField(
            model_name='initialdata',
            name='mb_set',
            field=models.FloatField(verbose_name='МБ'),
        ),
        migrations.AlterField(
            model_name='initialdata',
            name='rb_set',
            field=models.FloatField(verbose_name='РБ'),
        ),
        migrations.AlterField(
            model_name='initialdata',
            name='rf_set',
            field=models.FloatField(verbose_name='Референс'),
        ),
        migrations.AlterField(
            model_name='initialdata',
            name='time_execution_plan',
            field=models.FloatField(verbose_name='Срок выполнения по плану'),
        ),
        migrations.AlterField(
            model_name='initialdata',
            name='vnb_set',
            field=models.FloatField(verbose_name='ВНБ'),
        ),
    ]
